<a href="https://colab.research.google.com/github/Kirknasty54/Jackson_Kirkpatrick_ICP3/blob/main/Jackson_Kirkpatrick_ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [37]:
rand_vect = np.random.randint(1, 21, size=15)
print(f"Unaltered vector: {rand_vect}")
reshaped = rand_vect.reshape(3, 5)
print(f"Reshaped array: \n{reshaped}")
for i in range(reshaped.shape[0]):
  max_idx = np.argmax(reshaped[i])
  reshaped[i, max_idx] = 0
print(f"Replaced max values\n{reshaped}")

Unaltered vector: [19 12  4 20  5  2  9 17 17  7  9  6  7  1 14]
Reshaped array: 
[[19 12  4 20  5]
 [ 2  9 17 17  7]
 [ 9  6  7  1 14]]
Replaced max values
[[19 12  4  0  5]
 [ 2  9  0 17  7]
 [ 9  6  7  1  0]]


In [47]:
twod_array = np.empty((4, 3), dtype=np.int32)
print(twod_array)
print(twod_array.shape)
print(type(twod_array))
print(twod_array.dtype)

[[ 1203046938       22867           0]
 [          0 -1998922768       30948]
 [-1999045376       30948   388253571]
 [-1596347950 -1998922704       30948]]
(4, 3)
<class 'numpy.ndarray'>
int32


In [49]:
array = np.array([[0, 1, 2],
                  [3, 4, 5]])
diagonal_sum = np.trace(array)
print(diagonal_sum)

7


In [70]:
odds = np.arange(11, 71, 2)
evens = np.arange(10, 71, 2)
print(f"Odd array:\n{odds}")
print(f"Even array:\n{evens}")

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
add = array1 + array2
subtract = array1 - array2
multiplication = array1 * array2
print(f"Element-wise adition:{add}")
print(f"Element-wise subtraction:{subtract}")
print(f"Element-wise multiplication:{multiplication}")

given_array = np.array([[5.54, 3.38, 7.99],
                        [3.54, 4.38, 6.99],
                        [1.54, 2.39, 9.29]])
row_sorted = np.sort(given_array, axis=1)
col_sorted = np.sort(given_array, axis=0)
print(f"Sorted by row:\n{row_sorted}")
print(f"Sorted by column:\n{col_sorted}")

Odd array:
[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]
Even array:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]
Element-wise adition:[ 7  9 11 13 15]
Element-wise subtraction:[-5 -5 -5 -5 -5]
Element-wise multiplication:[ 6 14 24 36 50]
Sorted by row:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
Sorted by column:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [71]:
missing_data_array  = np.array([[4, 2, np.nan, 1],
                                [11, 12, 14, 9],
                                [5, np.nan, 1, np.nan]])
missing_data = np.isnan(missing_data_array)
print(missing_data)

[[False False  True False]
 [False False False False]
 [False  True False  True]]
